host: 0.0.0.0
title: First Generation First Admin
email: figgchristian@gmail.com
description: >-
  Admin site used by the FGF team.
baseurl: ""
url: "https://admin.firstgenfirst.org"

exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - gulpfile.js
  - vendor/